//* NEWBIE Images
import {
  N1,
  N2,
  N3,
  N4,
  N5,
  N6,
  N7,
  N8,
  N9,
  N10,
  N11,
  N12,
  N13,
  N14,
  N15,
  N16,
  N17,
  N18,
} from "../../assets/images/app/1-newbie";

//* JUNIOR Images
import { N21, N22 } from "../../assets/images/app/2-junior";

import { LEVEL, TAGS, ROUTES, REPO } from "./constants";

export const AppData = [
  //* N E W B I E
  {
    image: N1,
    name: "Result Summary",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.resultSummary}`,
    code: `${REPO}1-${LEVEL.newbie.name}/1-${ROUTES.newbie.resultSummary}`,
  },
  {
    image: N2,
    name: "Product Preview Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.productCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/2-${ROUTES.newbie.productCard}`,
  },
  {
    image: N3,
    name: "NFT Preview Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.nftCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/3-${ROUTES.newbie.nftCard}`,
  },
  {
    image: N4,
    name: "Interactive Rating",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.interactiveRating}`,
    code: `${REPO}1-${LEVEL.newbie.name}/4-${ROUTES.newbie.interactiveRating}`,
  },
  {
    image: N5,
    name: "Stats Preview Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.statsCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/5-${ROUTES.newbie.statsCard}`,
  },
  {
    image: N6,
    name: "Order Summary",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.orderSummary}`,
    code: `${REPO}1-${LEVEL.newbie.name}/6-${ROUTES.newbie.orderSummary}`,
  },
  {
    image: N7,
    name: "QR Code",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.qrCode}`,
    code: `${REPO}1-${LEVEL.newbie.name}/7-${ROUTES.newbie.qrCode}`,
  },
  {
    image: N8,
    name: "Three Column Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.threeColumnCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/8-${ROUTES.newbie.threeColumnCard}`,
  },
  {
    image: N9,
    name: "Profile Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.profileCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/9-${ROUTES.newbie.profileCard}`,
  },
  {
    image: N10,
    name: "FAQs Accordion Card",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.faqAccordion}`,
    code: `${REPO}1-${LEVEL.newbie.name}/10-${ROUTES.newbie.faqAccordion}`,
  },
  {
    image: N11,
    name: "Social Proof Section",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.socialProofSection}`,
    code: `${REPO}1-${LEVEL.newbie.name}/11-${ROUTES.newbie.socialProofSection}`,
  },
  {
    image: N12,
    name: "Article Preview Component",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.articlePreview}`,
    code: `${REPO}1-${LEVEL.newbie.name}/12-${ROUTES.newbie.articlePreview}`,
  },
  {
    image: N13,
    name: "Four Card Feature Section",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.fourCardFeature}`,
    code: `${REPO}1-${LEVEL.newbie.name}/13-${ROUTES.newbie.fourCardFeature}`,
  },
  {
    image: N14,
    name: "Base Apparel Coming Soon",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.baseApparel}`,
    code: `${REPO}1-${LEVEL.newbie.name}/14-${ROUTES.newbie.baseApparel}`,
  },
  {
    image: N15,
    name: "Intro Component with SignIn Form",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.introComponent}`,
    code: `${REPO}1-${LEVEL.newbie.name}/15-${ROUTES.newbie.introComponent}`,
  },
  {
    image: N16,
    name: "Single Price Grid",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.singlePriceGrid}`,
    code: `${REPO}1-${LEVEL.newbie.name}/16-${ROUTES.newbie.singlePriceGrid}`,
  },
  {
    image: N17,
    name: "Ping Coming Soon Page",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.pingComingSoon}`,
    code: `${REPO}1-${LEVEL.newbie.name}/17-${ROUTES.newbie.pingComingSoon}`,
  },
  {
    image: N18,
    name: "Huddle Landing Page",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.huddleLandingPage}`,
    code: `${REPO}1-${LEVEL.newbie.name}/18-${ROUTES.newbie.huddleLandingPage}`,
  },
  //* J U N I O R
  {
    image: N21,
    name: "Newsletter Sign Up",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.junior,
    link: `${LEVEL.junior.name}/${ROUTES.junior.newsletterSignUp}`,
    code: `${REPO}2-${LEVEL.junior.name}/1-${ROUTES.junior.newsletterSignUp}`,
  },
  {
    image: N22,
    name: "Age Calculator App",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.junior,
    link: `${LEVEL.junior.name}/${ROUTES.junior.ageCalculatorApp}`,
    code: `${REPO}2-${LEVEL.junior.name}/2-${ROUTES.junior.ageCalculatorApp}`,
  },
];
