import { N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N11, N12, N13 } from "../../assets/images/app";

import { LEVEL, TAGS, ROUTES, REPO } from "./constants";

export const AppData = [
  {
    image: N1,
    name: "Result Summary",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.resultSummary}`,
    code: `${REPO}1-${LEVEL.newbie.name}/1-${ROUTES.newbie.resultSummary}`,
  },
  {
    image: N2,
    name: "Product Preview Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.productCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/2-${ROUTES.newbie.productCard}`,
  },
  {
    image: N3,
    name: "NFT Preview Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.nftCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/3-${ROUTES.newbie.nftCard}`,
  },
  {
    image: N4,
    name: "Interactive Rating",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.interactiveRating}`,
    code: `${REPO}1-${LEVEL.newbie.name}/4-${ROUTES.newbie.interactiveRating}`,
  },
  {
    image: N5,
    name: "Stats Preview Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.statsCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/5-${ROUTES.newbie.statsCard}`,
  },
  {
    image: N6,
    name: "Order Summary",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.orderSummary}`,
    code: `${REPO}1-${LEVEL.newbie.name}/6-${ROUTES.newbie.orderSummary}`,
  },
  {
    image: N7,
    name: "QR Code",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.qrCode}`,
    code: `${REPO}1-${LEVEL.newbie.name}/7-${ROUTES.newbie.qrCode}`,
  },
  {
    image: N8,
    name: "Three Column Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.threeColumnCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/8-${ROUTES.newbie.threeColumnCard}`,
  },
  {
    image: N9,
    name: "Profile Card",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.profileCard}`,
    code: `${REPO}1-${LEVEL.newbie.name}/9-${ROUTES.newbie.profileCard}`,
  },
  {
    image: N10,
    name: "FAQs Accordion Card",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.faqAccordion}`,
    code: `${REPO}1-${LEVEL.newbie.name}/10-${ROUTES.newbie.faqAccordion}`,
  },
  {
    image: N11,
    name: "Social Proof Section",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.socialProofSection}`,
    code: `${REPO}1-${LEVEL.newbie.name}/11-${ROUTES.newbie.socialProofSection}`,
  },
  {
    image: N12,
    name: "Article Preview Component",
    tags: [TAGS.html, TAGS.css, TAGS.js],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.articlePreview}`,
    code: `${REPO}1-${LEVEL.newbie.name}/12-${ROUTES.newbie.articlePreview}`,
  },
  {
    image: N13,
    name: "Four Card Feature Section",
    tags: [TAGS.html, TAGS.css],
    level: LEVEL.newbie,
    link: `${LEVEL.newbie.name}/${ROUTES.newbie.fourCardFeature}`,
    code: `${REPO}1-${LEVEL.newbie.name}/13-${ROUTES.newbie.fourCardFeature}`,
  },
];
